### PR TITLE
Add support for IntelliChlor primary and secondary body output percentage controls

### PR DESCRIPTION
**Pull request by philipflesher**
IntelliChlor has the ability to set both a primary and a secondary body of water (e.g., pool and spa) as having different output percentages. Previous implementation only worked for the primary body; this change allows for viewing and setting of both primary and secondary bodies.

### CODE REVIEW

**Comment by philipflesher** [comment]
@dwradcliffe -- This PR also includes the same fix you already have in yours that removes the CR/LF in the transport write. Looks like the exact same fix to me, so hopefully can be ignored.

**Comment by dwradcliffe** [comment]
Thanks @philipflesher this looks pretty good. I want to boot up my system and double check this works as expected so it might be a couple days until I have a chance to do that.

**Comment by philipflesher** [comment]
Hi @dwradcliffe -- have you had a chance to check this out yet?

**Comment by dwradcliffe** [comment]
Hey sorry it's been too cold to go plug in my system 😆 Maybe this weekend.

**Comment by philipflesher** [comment]
@dwradcliffe don't suppose you've been able to test yet?

In other news, I upgraded to HA 2024.2 and see a couple of other small things being mentioned in logs now as deprecated. I will probably try to make these changes as well.

**Comment by dwradcliffe** [comment]
Looks good, thanks for your patience!

**Pull request merged**
